### ISSUE TITLE
请教下底部tabbar是自己实现的吗？好像不是官方的

### ISSUE THREAD

**Issue by nunu-sudo** [TheBund1st/jonsnow-issue#16]

**Comment by codingwesley** [comment]
对的 官方不支持，自己DIY的

**Comment by nunu-sudo** [comment]
> 对的 官方不支持，自己DIY的

怎么实现的，能参考下吗，感觉好美观，哈哈哈

**Comment by codingwesley** [comment]
你把公司的内部邮箱email给我，我加你“闪光”项目组权限

**Comment by nunu-sudo** [comment]
> 你把公司的内部邮箱email给我，我加你“闪光”项目组权限

bingshuai.lu@thoughtworks.com
